### ISSUE TITLE
No module named 'urllib2' in python3+

### ISSUE THREAD

**Issue by pgergov** [HackSoftware/cookiecutter-django-ansible#34]
```
╰─$ ansible-galaxy install -r requirements.yml
ERROR! Unexpected Exception: 'ImportError' object has no attribute 'message'
the full traceback was:

Traceback (most recent call last):
  File "/usr/local/bin/ansible-galaxy", line 79, in <module>
    mycli = getattr(__import__("ansible.cli.%s" % sub, fromlist=[myclass]), myclass)
  File "/usr/local/lib/python3.5/dist-packages/ansible/cli/galaxy.py", line 37, in <module>
    from ansible.galaxy.api import GalaxyAPI
  File "/usr/local/lib/python3.5/dist-packages/ansible/galaxy/api.py", line 30, in <module>
    from urllib2 import quote as urlquote, HTTPError
ImportError: No module named 'urllib2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/ansible-galaxy", line 85, in <module>
    if e.message.endswith(' %s' % sub):
AttributeError: 'ImportError' object has no attribute 'message'

```

**Comment by Ivaylo-Bachvarov** [comment]
I will put a link to "How to install ansible" in the README.md
